package fr.garnier.stage_1;

import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Paths;


public class Main {
    public static void Main(String[] args){
        generateJavaCode();
    }

    private static void generateJavaCode() {
        MethodSpec constructorSpec = MethodSpec.constructorBuilder()
                .addParameter(TypeName.INT, "aircraftId", Modifier.FINAL)
                .addStatement("this.aircraftId = aircraftId")
                .addModifiers(Modifier.PUBLIC).build();

        MethodSpec getAircraftIdMethod = MethodSpec.methodBuilder("getAircraftId")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.INT)
                .addStatement("return aircraftId")
                .build();

        TypeSpec flightPlanSpec = TypeSpec.classBuilder("FlightMsg255")
                .addModifiers(Modifier.PUBLIC)
                .addField(TypeName.INT, "aircraftId", Modifier.PRIVATE, Modifier.FINAL)
                .addMethod(getAircraftIdMethod)
                .addMethod(constructorSpec)
                .build();

        JavaFile javaFile = JavaFile.builder("com.mvpjava.javapoet.autogen", flightPlanSpec)
                .addFileComment("AUTO_GENERATED BY JavaPoet")
                .build();

        try {
            javaFile.writeTo(Paths.get("./src/main/java"));//root maven source
        } catch (IOException ex) {
            System.out.println("An exception ... Really!?! " + ex.getMessage());
        }
    }

}