package fr.garnier.javapoet;

import com.squareup.javapoet.*;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Paths;



public class main {
    public static void main(String[] args){
        generateJavaCode();
    }

    private static void generateJavaCode() {

        generationMain();
        generationStatus();
        
        generationCommand();
    }

    private static void generationCommand() {
    }

    private static void generationStatus() {
        TypeSpec status = TypeSpec.enumBuilder("Status")
                .addModifiers(Modifier.PUBLIC)
                .addEnumConstant("NOTREADY")
                .addEnumConstant("READY")
                .addEnumConstant("STOPPED")
                .build();


        JavaFile javaFile = JavaFile.builder("fr.garnier.javapoet", status)
                .addFileComment("AUTO_GENERATED BY JavaPoet")
                .build();

        writeFile(javaFile,"./target/generated-sources/annotations");
    }

    private static void generationMain() {
        MethodSpec getPlugin = MethodSpec.methodBuilder("getPlugin")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(TypeName.OBJECT)
                .addStatement("return plugin")
                .build();

        MethodSpec onEnable = MethodSpec.methodBuilder("onEnable")
                .addModifiers(Modifier.PUBLIC)
                //.addAnnotation(Override.class)
                .build();

        MethodSpec onDisable = MethodSpec.methodBuilder("onDisable")
                .addModifiers(Modifier.PUBLIC)
                .build();

        TypeSpec main = TypeSpec.classBuilder("PluginMain")
                .addModifiers(Modifier.PUBLIC)
                .addField(TypeName.OBJECT, "plugin", Modifier.PRIVATE, Modifier.STATIC)
                .addMethod(getPlugin)
                .addMethod(onEnable)
                .addMethod(onDisable)
                .build();

        JavaFile javaFile = JavaFile.builder("fr.garnier.javapoet", main)
                .addFileComment("AUTO_GENERATED BY JavaPoet")
                .build();

        writeFile(javaFile,"./target/generated-sources/annotations");
    }

    private static void writeFile(JavaFile javaFile, String path) {
        try {
            javaFile.writeTo(Paths.get(path));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }


}