package fr.garnier.javapoet;

import com.squareup.javapoet.*;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Paths;



public class main {
    public static void main(String[] args){
        generateJavaCode();
    }

    private static void generateJavaCode() {

        MethodSpec getPlugin = MethodSpec.methodBuilder("getPlugin")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(TypeName.OBJECT)
                .addStatement("return plugin")
                .build();

        MethodSpec onEnable = MethodSpec.methodBuilder("onEnable")
                .addModifiers(Modifier.PUBLIC)
                //.addAnnotation(Override.class)
                .build();

        MethodSpec onDisable = MethodSpec.methodBuilder("onDisable")
                .addModifiers(Modifier.PUBLIC)
                .build();

        TypeSpec flightPlanSpec = TypeSpec.classBuilder("PluginMain")
                .addModifiers(Modifier.PUBLIC)
                .addField(TypeName.OBJECT, "plugin", Modifier.PRIVATE, Modifier.STATIC)
                .addMethod(getPlugin)
                .addMethod(onEnable)
                .addMethod(onDisable)
                .build();

        TypeSpec status = TypeSpec.enumBuilder("status")
                .addModifiers(Modifier.PUBLIC)
                .addEnumConstant("NOTREADY")
                .addEnumConstant("READY")
                .addEnumConstant("STOPPED")
                .build();

        JavaFile javaFile = JavaFile.builder("fr.garnier.javapoet.autogen", flightPlanSpec)
                .addFileComment("AUTO_GENERATED BY JavaPoet")
                .build();

        try {
            javaFile.writeTo(Paths.get("./src/main/java/fr/garnier/javapoet"));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }

        javaFile = JavaFile.builder("fr.garnier.javapoet.autogen", status)
                .addFileComment("AUTO_GENERATED BY JavaPoet")
                .build();

        try {
            javaFile.writeTo(Paths.get("./src/main/java/fr/garnier/javapoet"));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }

}